---
LoadingUltima:
  name: Loading
  workflow: Ultima
  sorted: 0
  lab_activity: true
  sti_type: SetDescriptorsTask
Opentrons:
  name: Opentrons
  workflow: Ultima
  sorted: 0
  lab_activity: true
  sti_type: SetDescriptorsTask
Amp:
  name: Amp
  workflow: Ultima
  sorted: 1
  lab_activity: true
  sti_type: SetDescriptorsTask

