language: ruby
# We don't specify a list of ruby versions, as Travis will fall back to .ruby-version
dist: xenial
sudo: required
services:
  - mysql
  - xvfb
addons:
  chrome: stable
  apt:
    packages:
    - haveged
cache:
  bundler: true
bundler_args: "--without warehouse deployment"
env:
  global:
  - TZ=Europe/London
  - CUCUMBER_FORMAT=summary
before_install:
- mv config/aker.yml.example config/aker.yml
- nvm install
- node --version
- yarn install
- yes | gem update --system --force # use bundler 2.0 https://docs.travis-ci.com/user/languages/ruby/#bundler-20
- gem install bundler # use bundler 2.0 https://docs.travis-ci.com/user/languages/ruby/#bundler-20
jobs:
  include:
  - stage: test
    if: type = cron
    before_script:
    - RAILS_ENV=test bundle exec rails webdrivers:chromedriver:update
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script: "xvfb-run -a ./run_coverage"
    name: Coverage
    after_script:
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
    env:
    - RAILS_ENV=cucumber
    - CI_NODE_TOTAL=2
    - CI_NODE_INDEX=1
    before_script:
    - RAILS_ENV=test bundle exec rails webdrivers:chromedriver:update -r webdrivers
    - bundle exec rake assets:precompile
    - bundle exec rake db:setup
    name: Cucumber Test 2
    script: xvfb-run -a bundle exec rake knapsack:cucumber
  - stage: build
    if: tag IS present
    script: "./compile-build"
    name: Compile Build
    deploy:
      provider: releases
      file: release.tar.gz
      file_glob: true
      skip_cleanup: true
      on:
        tags: true
        repo: sanger/sequencescape
      api_key:
        secure: eWwbjG2LpK3cTHbqJfccIpcNj0PUl2YqGRYVAOQX+YPUtjOjnR4hqDMIUJTCVAHQ8PUC3yh/H7Sf4F7I5DQ5SdhY2Yeiusucig3V8yUdO6oHrpgaN2r9Nd/nM/vRxL7oVCI84Ahhu5mKL3x1PayTTpRjiu1KqL/BMbV//6s5jBs=
notifications:
  slack:
    secure: cYYbPW8aReWrX5bqoxuCAQJgDb77JZ47dnTVdz1cna7iYfG4sC44BhVwz1ldkp1O4ihUPHynctwjiFaOs+Ob6jBCwSjopawE6R3efW+ZbrpdX+tHSt1tm6nJ4/MTvp+qs1KClPExBc94uAp0q+fqs6QQeJVDHaHy+VBPHXhCP3U=
