language: ruby
# We don't specify a list of ruby versions, as Travis will fall back to .ruby-version
dist: xenial
sudo: required
services:
  - mysql
  - xvfb
addons:
  chrome: stable
  apt:
    packages:
    - haveged
cache:
  bundler: true
bundler_args: "--without warehouse deployment"
env:
  global:
  - TZ=Europe/London
  - CUCUMBER_FORMAT=DebugFormatter
before_install:
- mv config/aker.yml.example config/aker.yml
jobs:
  include:
  - stage: test
    if: type = cron
    before_script:
    - RAILS_ENV=test bundle exec rails webdrivers:chromedriver:update
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - "./cc-test-reporter before-build"
    script: "xvfb-run -a ./run_coverage"
    name: Coverage
    after_script:
    - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
  - if: type != cron
    script: bundle exec rubocop
    name: Rubocop
  - if: type != cron
    env:
    - RUBYOPT='-W0'
    before_script:
    - bundle exec rake assets:precompile
    - bundle exec rake db:setup
    script: bundle exec rake test
    name: Rake Test
  - if: type != cron
    env:
    before_script:
    - RAILS_ENV=test bundle exec rails webdrivers:chromedriver:update -r webdrivers
    - bundle exec rake assets:precompile
    - bundle exec rake db:setup
    script: xvfb-run -a bundle exec rspec
    name: Rspec
  - if: type != cron
    env:
    - RAILS_ENV=cucumber
    - CI_NODE_TOTAL=2
    - CI_NODE_INDEX=0
    before_script:
    - RAILS_ENV=test bundle exec rails webdrivers:chromedriver:update -r webdrivers
    - bundle exec rake assets:precompile
    - bundle exec rake db:setup
    name: Cucumber Test 1
    script: xvfb-run -a bundle exec rake knapsack:cucumber
  - if: type != cron
    env:
    - RAILS_ENV=cucumber
    - CI_NODE_TOTAL=2
    - CI_NODE_INDEX=1
    before_script:
    - RAILS_ENV=test bundle exec rails webdrivers:chromedriver:update -r webdrivers
    - bundle exec rake assets:precompile
    - bundle exec rake db:setup
    name: Cucumber Test 2
    script: xvfb-run -a bundle exec rake knapsack:cucumber
  - stage: build
    if: tag IS present
    script: "./compile-build"
    name: Compile Build
    deploy:
      provider: releases
      file: release.tar.gz
      file_glob: true
      skip_cleanup: true
      on:
        tags: true
        repo: sanger/sequencescape
      api_key:
        secure: eWwbjG2LpK3cTHbqJfccIpcNj0PUl2YqGRYVAOQX+YPUtjOjnR4hqDMIUJTCVAHQ8PUC3yh/H7Sf4F7I5DQ5SdhY2Yeiusucig3V8yUdO6oHrpgaN2r9Nd/nM/vRxL7oVCI84Ahhu5mKL3x1PayTTpRjiu1KqL/BMbV//6s5jBs=
