language: ruby
rvm:
  - jruby-19mode
  - jruby-9.0.5.0
  - jruby-9.0.4.0
bundler_args: --without warehouse development deployment
before_install:
  - export TZ=Europe/London
before_script:
  - "bundle exec rake db:create RAILS_ENV=test"
  - "bundle exec rake db:test:load"
  - export CUCUMBER_FORMAT=progress
  - export RUBY_OPT=--profile
matrix:
  allow_failures:
    - rvm: jruby-9.0.5.0
