language: ruby
rvm:
  - jruby-9.1.7.0
  - 2.3.3
sudo: false
cache: bundler
jdk: oraclejdk8
bundler_args: --without warehouse deployment
env:
  - "DB_REQUIRED='true' RAILS_ENV=test TZ=Europe/London SUITE='rake test' RUBYOPT='-W0'" # RUBYOPT disables warnings turned on by default in rake 11. See note in README
  - "DB_REQUIRED='true' RAILS_ENV=test TZ=Europe/London SUITE='rspec'"
  - "DB_REQUIRED='true' RAILS_ENV=cucumber CI_NODE_TOTAL=2 CI_NODE_INDEX=0 JRUBY_OPTS='' CUCUMBER_FORMAT=progress TZ=Europe/London SUITE='rake knapsack:cucumber'"
  - "DB_REQUIRED='true' RAILS_ENV=cucumber CI_NODE_TOTAL=2 CI_NODE_INDEX=1 JRUBY_OPTS='' CUCUMBER_FORMAT=progress TZ=Europe/London SUITE='rake knapsack:cucumber'"
  - "SUITE=rubocop"
before_script:
  - 'if [[ "$DB_REQUIRED" == "true" ]]; then bundle exec rake db:setup; fi'
script:
  - "bundle exec $SUITE"
matrix:
  allow_failures:
  - rvm: 2.3.3
