# These purposes are used the end of scRNA Core Cell Extraction pipeline
# Added here to allow creation of the submission and request type records for
# scRNA Core cDNA Prep.
---
LRC Bank Seq:
  type: Tube::Purpose
  target_type: SampleTube
  stock_plate: false

LRC Bank Spare:
  type: Tube::Purpose
  target_type: SampleTube
  stock_plate: false

LRC Bank Input 1ml:
  type: Tube::Purpose
  target_type: SampleTube
  stock_plate: true

LRC Bank Input 0.8ml:
  type: Tube::Purpose
  target_type: SampleTube
  stock_plate: true
