---
OTR carrier barcode:
  name: OTR carrier barcode
  task: Opentrons
  workflow: Ultima
  kind: Text
  required: false
  sorter: 0
OTR carrier expiry:
  name: OTR carrier expiry
  task: Opentrons
  workflow: Ultima
  kind: Date
  required: false
  sorter: 1
Reaction mix 7 barcode:
  name: Reaction mix 7 barcode
  task: Opentrons
  workflow: Ultima
  kind: Text
  required: false
  sorter: 2
Reaction mix 7 expiry:
  name: Reaction mix 7 expiry
  task: Opentrons
  workflow: Ultima
  kind: Date
  required: false
  sorter: 3
NFW barcode:
  name: NFW barcode
  task: Opentrons
  workflow: Ultima
  kind: Text
  required: false
  sorter: 4
NFW expiry:
  name: NFW expiry
  task: Opentrons
  workflow: Ultima
  kind: Date
  required: false
  sorter: 5
Oil barcode:
  name: Oil barcode
  task: Opentrons
  workflow: Ultima
  kind: Text
  required: false
  sorter: 6
Oil expiry:
  name: Oil expiry
  task: Opentrons
  workflow: Ultima
  kind: Date
  required: false
  sorter: 7
Pipette carousel:
  name: Pipette carousel
  task: Opentrons
  workflow: Ultima
  kind: Text
  required: false
  sorter: 8
Opentrons Inst. Name:
  name: Opentrons Inst. Name
  task: Opentrons
  workflow: Ultima
  kind: Text
  required: true
  sorter: 9
Assign Control Bead Tube:
  name: Assign Control Bead Tube
  task: Amp
  workflow: Ultima
  kind: Text
  required: false
  sorter: 0
UG AMP Inst. Name:
  name: UG AMP Inst. Name
  task: Amp
  workflow: Ultima
  kind: Text
  required: true
  sorter: 1
