---
# Descriptors for Task - Loading
Workflow (Standard or Xp)	Standard:
  name: Workflow (Standard or Xp)	Standard
  task: Loading
  workflow: NovaSeq 6000 PE
  kind: Selection
  value: Standard
  selection:
    Standard: Standard
    XP: XP
  required: false
  sorter: 3
DPX1:
  name: DPX1
  task: Loading
  workflow: NovaSeq 6000 PE
  kind: Text
  required: false
  sorter: 4
DPX2:
  name: DPX2
  task: Loading
  workflow: NovaSeq 6000 PE
  kind: Text
  required: false
  sorter: 5
DPX3:
  name: DPX3
  task: Loading
  workflow: NovaSeq 6000 PE
  kind: Text
  required: false
  sorter: 6
NovaSeq Xp Mainfold:
  name: NovaSeq Xp Mainfold
  task: Loading
  workflow: NovaSeq 6000 PE
  kind: Text
  required: false
  sorter: 7
Pipette Carousel:
  name: Pipette Carousel
  task: Loading
  workflow: NovaSeq 6000 PE
  kind: Text
  required: false
  sorter: 8
PhiX lot:
  name: PhiX lot
  task: Loading
  workflow: NovaSeq 6000 PE
  kind: Text
  required: false
  sorter: 9
PhiX %:
  name: PhiX %
  task: Loading
  workflow: NovaSeq 6000 PE
  kind: Text
  required: false
  sorter: 10
Lane loading concentration (pM):
  name: Lane loading concentration (pM)
  task: Loading
  workflow: NovaSeq 6000 PE
  kind: Text
  required: false
  sorter: 11
Comment:
  name: Comment
  task: Loading
  workflow: NovaSeq 6000 PE
  kind: Text
  required: false
  sorter: 12
