---
PN-1000215/PN-3000431 Dual Index Kit TT, Set A:
  name: PN-1000215/PN-3000431 Dual Index Kit TT, Set A
  tag_group_name: PN-1000215/PN-3000431 Dual Index Kit TT, Set A (i7)
  tag2_group_name: PN-1000215/PN-3000431 Dual Index Kit TT, Set A (i5)
PN-1000250 Dual Index Kit TN, Set A:
  name: PN-1000250 Dual Index Kit TN, Set A
  tag_group_name: PN-1000250 Dual Index Kit TN, Set A (i7)
  tag2_group_name: PN-1000250 Dual Index Kit TN, Set A (i5)
PN-1000251 Dual Index Kit TS, Set A:
  name: PN-1000251 Dual Index Kit TS, Set A
  tag_group_name: PN-1000251 Dual Index Kit TS, Set A (i7)
  tag2_group_name: PN-1000251 Dual Index Kit TS, Set A (i5)
PN-1000242/PN-3000483 Dual Index Kit NT, Set A:
  name: PN-1000242/PN-3000483 Dual Index Kit NT, Set A
  tag_group_name: PN-1000242/PN-3000483 Dual Index Kit NT, Set A (i7)
  tag2_group_name: PN-1000242/PN-3000483 Dual Index Kit NT, Set A (i5)
