batch_number:
  number_of_spaces: 25
  position_from: 1
  position_to: 25
  constant_value: "STD"
  right_justified: false
  order: 1
interface_code:
  number_of_spaces: 25
  position_from: 26
  position_to: 50
  constant_value: "BI"
  right_justified: false
  order: 2
voucher_type:
  number_of_spaces: 2
  position_from: 51
  position_to: 75
  constant_value: "LM"
  right_justified: false
  order: 3
trans_type:
  number_of_spaces: 2
  position_from: 76
  position_to: 77
  constant_value: "GL"
  right_justified: false
  order: 4
client:
  number_of_spaces: 25
  position_from: 78
  position_to: 102
  constant_value: "GR"
  right_justified: false
  order: 5
account:
  number_of_spaces: 25
  position_from: 103
  position_to: 127
  constant_value: "3730"
  right_justified: false
  order: 6
dim_1:
  number_of_spaces: 25
  position_from: 128
  position_to: 152
  constant_value: "0223"
  right_justified: false
  order: 7
dim_2:
  number_of_spaces: 25
  position_from: 153
  position_to: 177
  right_justified: false
  order: 8
  dynamic_attribute: :project_cost_code
dim_3:
  number_of_spaces: 25
  position_from: 178
  position_to: 202
  right_justified: false
  order: 9
  dynamic_attribute: :fin_product_code
dim_6:
  number_of_spaces: 25
  position_from: 253
  position_to: 277
  constant_value: "ILL"
  right_justified: false
  order: 10
tax_code:
  number_of_spaces: 25
  position_from: 303
  position_to: 327
  constant_value: "XX"
  right_justified: false
  order: 11
currency:
  number_of_spaces: 25
  position_from: 353
  position_to: 377
  constant_value: "GBP"
  right_justified: false
  order: 12
amount_input_currency:
  number_of_spaces: 20
  position_from: 380
  position_to: 399
  constant_value: "0"
  right_justified: true
  order: 13
amount_in_GBP:
  number_of_spaces: 20
  position_from: 400
  position_to: 419
  constant_value: "0"
  right_justified: true
  order: 14
value_1:
  number_of_spaces: 20
  position_from: 431
  position_to: 450
  right_justified: false
  order: 15
  dynamic_attribute: :units
descriptions:
  number_of_spaces: 255
  position_from: 491
  position_to: 745
  right_justified: false
  order: 16
  dynamic_attribute: :fin_product_description
transaction_date:
  number_of_spaces: 8
  position_from: 746
  position_to: 753
  right_justified: false
  order: 17
  dynamic_attribute: :request_passed_date
voucher_date:
  number_of_spaces: 8
  position_from: 754
  position_to: 761
  right_justified: false
  order: 18
  dynamic_attribute: :request_passed_date
