plate_default: &plate_default
  heading: "Default Plate"
  asset_type: "plate"
  columns:
    - :sanger_plate_id
    - :well
    - :sanger_sample_id
    - :supplier_name
    - :retention_instruction
    - :reference_genome
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :sample_ebi_accession_number
    - :donor_id
    - :phenotype
    - :control_type
plate_default_with_h12_empty:
  <<: *plate_default
  heading: "Default Plate with H12 empty"
  invalid_wells: ["H12"]
plate_full:
  heading: "Full Plate"
  asset_type: "plate"
  columns:
    - :sanger_plate_id
    - :well
    - :sanger_sample_id
    - :supplier_name
    - :retention_instruction
    - :reference_genome
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :genotype
    - :phenotype
    - :age
    - :developmental_stage
    - :cell_type
    - :disease_state
    - :compound
    - :dose
    - :immunoprecipitate
    - :growth_condition
    - :rnai
    - :organism_part
    - :time_point
    - :treatment
    - :subject
    - :disease
    - :sample_ebi_accession_number
    - :donor_id
    - :control_type
plate_rnachip:
  heading: "RNA/ChIP Plate"
  asset_type: "plate"
  columns:
    - :sanger_plate_id
    - :well
    - :sanger_sample_id
    - :supplier_name
    - :retention_instruction
    - :reference_genome
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :date_of_sample_collection
    - :dna_source
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :phenotype
    - :developmental_stage
    - :cell_type
    - :immunoprecipitate
    - :organism_part
    - :sample_ebi_accession_number
    - :donor_id
plate_library:
  heading: "Library Plate - custom tags"
  asset_type: "library_plate"
  columns:
    - :sanger_plate_id
    - :well
    - :sanger_sample_id
    - :supplier_name
    - :i7
    - :i5
    - :reference_genome
    - :library_type
    - :insert_size_from
    - :insert_size_to
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :genotype
    - :phenotype
    - :age
    - :developmental_stage
    - :cell_type
    - :disease_state
    - :compound
    - :dose
    - :immunoprecipitate
    - :growth_condition
    - :rnai
    - :organism_part
    - :time_point
    - :treatment
    - :subject
    - :disease
    - :sample_ebi_accession_number
    - :donor_id
    - :primer_panel
plate_dual_index_tag_library:
  heading: "Library Plate - dual index tag plate"
  asset_type: "library_plate"
  columns:
    - :sanger_plate_id
    - :well
    - :sanger_sample_id
    - :supplier_name
    - :dual_index_tag_set
    - :dual_index_tag_well
    - :reference_genome
    - :library_type
    - :insert_size_from
    - :insert_size_to
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :genotype
    - :phenotype
    - :age
    - :developmental_stage
    - :cell_type
    - :disease_state
    - :compound
    - :dose
    - :immunoprecipitate
    - :growth_condition
    - :rnai
    - :organism_part
    - :time_point
    - :treatment
    - :subject
    - :disease
    - :sample_ebi_accession_number
    - :donor_id
plate_chromium_library:
  heading: "Chromium Library Plate"
  asset_type: "library_plate"
  columns:
    - :sanger_plate_id
    - :well
    - :sanger_sample_id
    - :supplier_name
    - :chromium_single_index_tag_group
    - :chromium_tag_well
    - :reference_genome
    - :library_type
    - :insert_size_from
    - :insert_size_to
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :genotype
    - :phenotype
    - :age
    - :developmental_stage
    - :cell_type
    - :disease_state
    - :compound
    - :dose
    - :immunoprecipitate
    - :growth_condition
    - :rnai
    - :organism_part
    - :time_point
    - :treatment
    - :subject
    - :disease
    - :sample_ebi_accession_number
    - :donor_id
plate_bioscan:
  heading: "Bioscan Plate"
  asset_type: "plate"
  columns:
    - :sanger_plate_id
    - :well
    - :sanger_sample_id
    - :bioscan_supplier_name
    - :retention_instruction
    - :cohort
    - :country_of_origin
    - :date_of_sample_collection
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description_specimen_plate_barcode
    - :sample_type
    - :donor_id
    - :bioscan_control_type
plate_anospp:
  heading: "ANOSPP Plate"
  asset_type: "plate"
  columns:
    - :sanger_plate_id
    - :well
    - :sanger_sample_id
    - :supplier_name
    - :retention_instruction
    - :cohort
    - :country_of_origin
    - :date_of_sample_collection
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description_specimen_plate_barcode_mandatory
    - :sample_type
    - :donor_id
    - :control_type
plate_scrna_core_pools:
  heading: "scRNA Core Pools Plate"
  asset_type: "plate"
  rows_per_well: 150 # this is a guess at the largest number of samples that will be pooled together
  columns:
    - :sanger_plate_id
    - :well
    - :sanger_sample_id
    - :supplier_name
    - :donor_id_mandatory
    - :date_of_sample_collection
    - :country_of_origin
    - :gender
    - :phenotype
    - :sample_ebi_accession_number
    - :sample_taxon_id
    - :sample_common_name
tube_default:
  heading: "Default Tube"
  asset_type: "1dtube"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :supplier_name
    - :reference_genome
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :sample_ebi_accession_number
    - :donor_id
    - :phenotype
tube_full:
  heading: "Full Tube"
  asset_type: "1dtube"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :supplier_name
    - :reference_genome
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :genotype
    - :phenotype
    - :age
    - :developmental_stage
    - :cell_type
    - :disease_state
    - :compound
    - :dose
    - :immunoprecipitate
    - :growth_condition
    - :rnai
    - :organism_part
    - :time_point
    - :treatment
    - :subject
    - :disease
    - :sample_ebi_accession_number
    - :donor_id
tube_rnachip:
  heading: "RNA/ChIP Tube"
  asset_type: "1dtube"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :supplier_name
    - :reference_genome
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :date_of_sample_collection
    - :dna_source
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :phenotype
    - :developmental_stage
    - :cell_type
    - :immunoprecipitate
    - :organism_part
    - :sample_ebi_accession_number
    - :donor_id
tube_multiplexed_library:
  heading: "Multiplexed Library Tube"
  asset_type: "multiplexed_library"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :supplier_name
    - :tag_group
    - :tag_index
    - :tag2_group
    - :tag2_index
    - :reference_genome
    - :library_type
    - :insert_size_from
    - :insert_size_to
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :sample_ebi_accession_number
    - :donor_id
    - :phenotype
    - :primer_panel
    - :control_type
tube_library_with_tag_sequences:
  heading: "Library Tube with Tag Sequences"
  asset_type: "library"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :supplier_name
    - :i7
    - :i5
    - :reference_genome
    - :library_type
    - :insert_size_from
    - :insert_size_to
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :sample_ebi_accession_number
    - :donor_id
    - :phenotype
    - :primer_panel
tube_chromium_library:
  heading: "Chromium Library Tube"
  asset_type: "library"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :supplier_name
    - :chromium_tag_group
    - :chromium_tag_well
    - :reference_genome
    - :library_type
    - :insert_size_from
    - :insert_size_to
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :sample_ebi_accession_number
    - :donor_id
    - :phenotype
tube_multiplexed_library_with_tag_sequences:
  heading: "Multiplexed Library Tube with Tag Sequences"
  asset_type: "multiplexed_library"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :supplier_name
    - :i7
    - :i5
    - :reference_genome
    - :library_type
    - :insert_size_from
    - :insert_size_to
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :sample_ebi_accession_number
    - :donor_id
    - :phenotype
    - :primer_panel
    - :control_type
tube_multiplexed_chromium_library:
  heading: "Multiplexed Chromium Library Tube"
  asset_type: "multiplexed_library"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :supplier_name
    - :chromium_tag_group
    - :chromium_tag_well
    - :reference_genome
    - :library_type
    - :insert_size_from
    - :insert_size_to
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :sample_ebi_accession_number
    - :donor_id
    - :phenotype
tube_rack_default:
  heading: "Default Tube Rack"
  asset_type: "tube_rack"
  columns:
    - :tube_barcode
    - :sanger_sample_id
    - :supplier_name
    - :reference_genome
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :sample_ebi_accession_number
    - :donor_id
    - :phenotype
long_read:
  heading: "Long Read"
  asset_type: "1dtube"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :supplier_name
    - :volume
    - :concentration
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_ebi_accession_number
    - :phenotype
    - :donor_id
    - :genome_size
    - :library_type_long_read
    - :country_of_origin
    - :date_of_sample_collection
long_read_plate:
  heading: "Long Read Plate"
  asset_type: "plate"
  columns:
    - :sanger_plate_id
    - :well
    - :sanger_sample_id
    - :supplier_name
    - :retention_instruction
    - :volume
    - :concentration
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_ebi_accession_number
    - :phenotype
    - :donor_id
    - :genome_size
    - :library_type_long_read
    - :country_of_origin
    - :date_of_sample_collection
heron:
  heading: "Heron"
  asset_type: "plate"
  columns:
    - :sanger_plate_id
    - :well
    - :sanger_sample_id
    - :supplier_name
    - :retention_instruction
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :genotype
    - :phenotype
    - :age
    - :developmental_stage
    - :cell_type
    - :disease_state
    - :compound
    - :dose
    - :immunoprecipitate
    - :growth_condition
    - :rnai
    - :organism_part
    - :time_point
    - :treatment
    - :subject
    - :disease
    - :sample_ebi_accession_number
    - :control_type
    - :priority
cardinal:
  heading: "Cardinal"
  asset_type: "1dtube"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :supplier_name
    - :volume
    - :collected_by_for_cardinal
scrna_core:
  heading: "scRNA Core"
  asset_type: "1dtube"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :collected_by_for_scrna_core
    - :donor_id_mandatory
    - :supplier_name
    - :volume
    - :retention_instruction
tube_controls:
  heading: "Control tubes"
  asset_type: "1dtube"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :supplier_name
    - :control_type
    - :collected_by_for_controls
tube_extraction:
  heading: "Extraction Tube"
  asset_type: "1dtube"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :supplier_name
    - :retention_instruction
    - :reference_genome
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :sample_ebi_accession_number
    - :donor_id
    - :phenotype
