plate_default:
  heading: "Default Plate"
  asset_type: "plate"
  columns:
    - :sanger_plate_id
    - :well
    - :sanger_sample_id
    - :supplier_name
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :sample_ebi_accession_number
    - :donor_id
    - :phenotype
plate_full:
  heading: "Full Plate"
  asset_type: "plate"
  columns:
    - :sanger_plate_id
    - :well
    - :sanger_sample_id
    - :supplier_name
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :genotype
    - :phenotype
    - :age
    - :developmental_stage
    - :cell_type
    - :disease_state
    - :compound
    - :dose
    - :immunoprecipitate
    - :growth_condition
    - :rnai
    - :rnai2
    - :organism_part
    - :time_point
    - :treatment
    - :subject
    - :disease
    - :sample_ebi_accession_number
    - :donor_id
plate_rnachip:
  heading: "RNA/ChIP Plate"
  asset_type: "plate"
  columns:
    - :sanger_plate_id
    - :well
    - :sanger_sample_id
    - :supplier_name
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :dna_source
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :phenotype
    - :developmental_stage
    - :cell_type
    - :immunoprecipitate
    - :organism_part
    - :sample_ebi_accession_number
    - :donor_id
tube_default:
  heading: "Default Tube"
  asset_type: "1dtube"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :supplier_name
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :sample_ebi_accession_number
    - :donor_id
    - :phenotype
tube_full:
  heading: "Full Tube"
  asset_type: "1dtube"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :supplier_name
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :genotype
    - :phenotype
    - :age
    - :developmental_stage
    - :cell_type
    - :disease_state
    - :compound
    - :dose
    - :immunoprecipitate
    - :growth_condition
    - :rnai
    - :rnai2
    - :organism_part
    - :time_point
    - :treatment
    - :subject
    - :disease
    - :sample_ebi_accession_number
    - :donor_id
tube_rnachip:
  heading: "RNA/ChIP Tube"
  asset_type: "1dtube"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :supplier_name
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :dna_source
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :phenotype
    - :developmental_stage
    - :cell_type
    - :immunoprecipitate
    - :organism_part
    - :sample_ebi_accession_number
    - :donor_id
tube_multiplexed_library:
  heading: "Multiplexed Library Tube"
  asset_type: "multiplexed_library"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :tag_group
    - :tag_index
    - :tag2_group
    - :tag2_index
    - :library_type
    - :insert_size_from
    - :insert_size_to
    - :supplier_name
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :sample_ebi_accession_number
    - :donor_id
    - :phenotype
tube_library_with_tag_sequences:
  heading: "Library Tube with Tag Sequences"
  asset_type: "library"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :i7
    - :i5
    - :reference_genome
    - :library_type
    - :insert_size_from
    - :insert_size_to
    - :supplier_name
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :sample_ebi_accession_number
    - :donor_id
    - :phenotype
tube_multiplexed_library_with_tag_sequences:
  heading: "Multiplexed Library Tube with Tag Sequences"
  asset_type: "multiplexed_library"
  columns:
    - :sanger_tube_id
    - :sanger_sample_id
    - :i7
    - :i5
    - :reference_genome
    - :library_type
    - :insert_size_from
    - :insert_size_to
    - :supplier_name
    - :cohort
    - :volume
    - :concentration
    - :gender
    - :country_of_origin
    - :geographical_region
    - :ethnicity
    - :dna_source
    - :date_of_sample_collection
    - :date_of_sample_extraction
    - :sample_extraction_method
    - :sample_purified
    - :purification_method
    - :concentration_determined_by
    - :sample_storage_conditions
    - :mother
    - :father
    - :sibling
    - :gc_content
    - :sample_public_name
    - :sample_taxon_id
    - :sample_common_name
    - :sample_description
    - :sample_strain_att
    - :sample_type
    - :sample_ebi_accession_number
    - :donor_id
    - :phenotype
