development:
    amqp:
      url: amqp://localhost:5672/
      persistent: false
      burst_size: 1000
    accession_login: "accession_login"
    accession_url: http://localhost:9999/accession_service/
    accession_view_url: http://localhost:9999/view_accession/
    admin_email: admin@test.com
    exception_recipients: exceptions@test.com
    api_documentation_url: http://localhost:3000/documentation
    api_url: http://localhost:3000
    array_express_accession_login:
    asset_audits_url: http://localhost:3014/process_plates/new
    auth_cookie:
    authentication: local
    barcode_images_url: http://localhost:10000
    barcode_prefix: CT
    barcode_service_url: http://localhost:9998/barcode_service.wsdl
    delayed_job:
      study_report_priority: 100
      submission_process_priority: 0
    disable_accession_check: true
    disable_api_authentication: true
    ega_accession_login: "ega_accession_login"
    era_accession_login: "era_accession_login"
    ldap_port: 13890
    ldap_secure_port: 6360
    ldap_server: localhost
    login_url: /login
    mail_prefix: "[DEVELOPMENT]"
    pac_bio_instrument_api: http://example.com
    pac_bio_smrt_portal_api:  http://example.com
    pico_green_url: http://localhost:3003
    pipelines_url: http://localhost:3000
    plate_barcode_service: http://localhost:3011
    plate_volume_files: <%= Rails.root %>/data/plate_volume/
    proxy: http://example.com
    sanger_auth_service: http://localhost:9999/cgi-bin/prodsoft/SSO/isAuth.pl
    sanger_login_service: http://localhost:9999/LOGIN
    site_name: Projects (DEVELOPMENT)
    site_url: localhost:3000
    sanger_auth_freshness: 60
    studies_url: http://localhost:3000
    taxon_lookup_url: http://eutils.ncbi.nlm.nih.gov/entrez/eutils/
    tecan_files_location:  <%= Rails.root %>/data
    two_d_barcode_files_location: <%= Rails.root %>/data/2d
    xml_files_location: <%= Rails.root %>/data/
    data_sharing_contact:
      name: John Doe
      email: foo
    accession_local_key: abc
    sequencescape_email: sequencescape@example.com
    default_email_domain: example.com
    run_information_url: http://example.com/
    sso_logout_url: https://example.com/logout
    run_data_by_batch_id_url: http://example.com/search?query=
    sybr_green_images_url: http://example.com/batches/
    sequencing_admin_email: admin@example.com
    api:
      authorisation_code: development
      flush_response_at: 32768

test: &TEST
    amqp:
      url: amqp://localhost:5672/
      persistent: false
      burst_size: 1000
    accession_login: "accession_login"
    accession_url: http://localhost:9999/accession_service/
    accession_view_url: http://localhost:9999/view_accession/
    admin_email: admin@test.com
    exception_recipients: exceptions@test.com
    api_documentation_url: http://localhost:3000/documentation
    api_url: http://localhost:3000
    array_express_accession_login:
    auth_cookie:
    authentication: "local"
    barcode_images_url: http://example.com/deliberately_broken_url
    barcode_prefix: NT
    barcode_service_url: http://localhost:9998/barcode_service.wsdl
    disable_accession_check: false
    disable_api_authentication: true
    disable_web_proxy: true
    ega_accession_login: "ega_accession_login"
    era_accession_login: "era_accession_login"
    ldap_port: 389
    ldap_secure_port: 636
    ldap_server: "ldap.internal.sanger.ac.uk"
    login_url: /login
    mail_prefix: "[DEVELOPMENT]"
    pico_green_url: http://localhost:3003
    plate_barcode_service: http://localhost:9998/plate_barcode_service/
    plate_volume_files: <%= Rails.root %>/test/data/plate_volume/
    sanger_auth_service: http://localhost:9999/cgi-bin/prodsoft/SSO/isAuth.pl
    site_name: Projects (TEST)
    site_url: localhost:3000
    sanger_auth_freshness: 60
    auth_cookie:
    studies_url: http://localhost:3000
    taxon_lookup_url: http://eutils.ncbi.nlm.nih.gov/entrez/eutils/
    tecan_files_location:  <%= Rails.root %>/data
    verify_login_url: http://localhost:9999/cgi-bin/prodsoft/SSO/isAuth.pl
    xml_files_location: <%= Rails.root %>/data/
    data_sharing_contact:
      name: John Doe
      email: foo
    accession_local_key: abc
    sequencescape_email: sequencescape@example.com
    default_email_domain: example.com
    run_information_url: http://example.com/
    sso_logout_url: https://example.com/logout
    run_data_by_batch_id_url: http://example.com/search?query=
    sybr_green_images_url: http://example.com/batches/
    sequencing_admin_email: admin@example.com
    api:
      authorisation_code: cucumber
      flush_response_at: 32768

cucumber:
    <<: *TEST
