# Add feature flags to this file, example:
# dpl202_enable_angry_cat_feature: When enabled this will add an angry cat to all pages that will try to catch the mouse pointer
# The key should be lower case and snake case, and prefixed with the issue number to allow easy identification
dpl_395_2_enable_advanced_search_tab: Shows the Search tab in the top navigation bar

y25_442_make_api_key_mandatory: Makes API key mandatory for all API requests
