# Add feature flags to this file, example:
# dpl202_enable_angry_cat_feature: When enabled this will add an angry cat to all pages that will try to catch the mouse pointer
# The key should be lower case and snake case, and prefixed with the issue number to allow easy identification

dpl_395_2_enable_advanced_search_tab: Shows the Search tab in the top navigation bar

#Â Below is flagged off until some existing data that would violate the rule is fixed. Should be re-enabled in Y24-058.
y24_052_enable_data_release_timing_validation: Enables server-side validation that enforces a relationship between the values of two study metadata fields

y25_442_make_api_key_mandatory: Makes API key mandatory for all API requests

# Accessioning
y25_706_enable_accessioning: Enables the accessioning feature in the application
y25_714_skip_accessioning_tag_validation: Skips internal validation of accessioning tags prior to sample accessioning
y25_705_notify_on_internal_accessioning_validation_failures: Sends email to developers when internal validation fails during accessioning
y25_705_notify_on_external_accessioning_validation_failures: Sends email to developers when external validation fails during accessioning
