development:
  secret_key_base: development-environment-key

test:
  secret_key_base: test-environment-key
cucumber:
  secret_key_base: test-environment-key

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
