Dual Index Kit TN Set A 10Xgenomics i5_a Column Wise:
  adapter_type_name: Chromium
  tags:
    1: TCGCTAGCGA
    2: GACCTGCCTG
    3: TACTCACGCG
    4: GTACGAAGTG
    5: CTAGGGCAAA
    6: CCCTCACAAA
    7: AATTCGGGAA
    8: GAGGGAGCCA
    9: CAACCAACGA
    10: AGAGTCCATG
    11: GCCTACCGAA
    12: TTGAGCTGAG
    13: TCGCACCAAC
    14: TGGATGGGTG
    15: CACTACGGTT
    16: CGAGTAAGGA
    17: GCGAACTGAT
    18: CTGAGTCATT
    19: ACTGTGTCGC
    20: CTAACCTAAC
    21: TTTCGTAACT
    22: GTATGTCGGG
    23: GCAACACCTC
    24: AGTACGTGAG
    25: GAACTGGTAC
    26: TACTGAGAGA
    27: ACGCCTCTGA
    28: CAGATTGTAC
    29: CTTTGCTCCA
    30: TGAGGATCGC
    31: CCCTTTACCG
    32: CATCGCCCTC
    33: ACGATCGCGA
    34: CATGCATCAT
    35: GATTACTGAG
    36: GACCAATAGC
    37: AGCCATCAAT
    38: TCCTTACCAA
    39: CGCGTTTCCT
    40: GACTAACTGG
    41: CAAATTCCGG
    42: AACAACTAAG
    43: CAGTGCTGTT
    44: GAAACATATC
    45: GTGATCCCAA
    46: TCGTAGAGGA
    47: CAGTAAGTCT
    48: AGGTGTTAGT
    49: ATGCTACCGC
    50: TACGAATTGA
    51: CTACAGGGTC
    52: TCGTGAAATA
    53: GCATTTCATC
    54: ACAGTTAAGC
    55: TGTCGAGGAG
    56: ACGCGGAATA
    57: GTACGCCATG
    58: TCATCGGGCG
    59: AGGCCCAATG
    60: ATTCGTTCAA
    61: AGGGACCTGG
    62: CGGGTACTGG
    63: TTTAACTCGT
    64: GAGACCCTTC
    65: AGGAAGTCTG
    66: AAATTGAGCA
    67: CGATGCAAGC
    68: AGATGACATC
    69: GTAGCTGATA
    70: GTTGCGCCTC
    71: AACCCACCAA
    72: TGATGTTTGC
    73: AGAACTTCTT
    74: AGATAAACAG
    75: GCGCATAGGC
    76: GTCCCACTTA
    77: TCCTCCTGTA
    78: TAAATCTCTG
    79: TTGGTTACGT
    80: CCGCTCGTTA
    81: ACCCTCCCAT
    82: ATAGCATGCA
    83: ATGACCGATA
    84: CAGAAATATC
    85: TTGTACGTGG
    86: AAAGTGTTCT
    87: ACATTTGGAA
    88: CCACAGAACA
    89: CCTGGTGACA
    90: ACGGGCATGT
    91: CTGTCCGCGT
    92: CAAACGTCGC
    93: CCAGACTGCA
    94: GCGTCTACGC
    95: TCAATTGCAA
    96: TGCATAGTTT

Dual Index Kit TN Set A 10Xgenomics i7 - ColumnWise:
  adapter_type_name: Chromium
  tags:
    1: AGTATCTGCA
    2: CATAGCATGA
    3: AAGGGTTTAC
    4: AGCGCCTTGC
    5: GTCATCCTAT
    6: CCTGGCTATA
    7: TCATCGTTCT
    8: CGTTCCACAT
    9: TCTATGAGTG
    10: TACTGCAATA
    11: GCTTAAGCAA
    12: CAGTAATACA
    13: CGACCCAGTG
    14: ACTTGTTCGA
    15: GCACTACTGA
    16: ATCTTGCAGC
    17: TTATTGACAC
    18: TGGCTACCGG
    19: GTGATCTGGG
    20: ATAGAACCAC
    21: CATAGTTCGC
    22: AACCATTAGT
    23: GTTATCACGA
    24: CAGCTGTTAT
    25: GAACAACCTT
    26: ACGTTTGATT
    27: ATGCAAGATC
    28: TTACAATCGT
    29: TCACGTTGGG
    30: TTGCGGGACT
    31: CAGGCGAATA
    32: CTACGACTGA
    33: TCTCGAATGT
    34: TGGGTGCACA
    35: TCAAAGGGTT
    36: CTGCCTGGGT
    37: TAATCTTCGG
    38: GAGCGAAAGC
    39: TAAGTAGAAG
    40: GCTGGGATGC
    41: TTTGCTGGGT
    42: ACGAGCGGAA
    43: TCAAGTAAAG
    44: GAAAGCGCGC
    45: CCATCACCAC
    46: AGCATCACAT
    47: CGAGGAGCAT
    48: CCGTCGCTGA
    49: TCCGAATAAA
    50: CCATTGTAAG
    51: GCTGCTCCCA
    52: TGTTCGCGAA
    53: CCATTAGGCG
    54: ACCATTGCAC
    55: ATCACCGTTT
    56: AAGTTAGTAC
    57: GTTTGAAAGT
    58: TAGTAGTTTG
    59: ATCTGTAGTT
    60: GCGTAACGAT
    61: CTGGTGATAA
    62: GTTCTGGAAC
    63: GACCGCCTTT
    64: GACTCAGGGT
    65: GCACGTGACA
    66: GATGGAAGGT
    67: ATGGCGCAAA
    68: TGTCAGTAAG
    69: CGTTGGTCCG
    70: CGGACGACCT
    71: TCCCGACCTG
    72: TGCACAAGCG
    73: GTCGTTGCCT
    74: ACAGGTTACG
    75: TAATGGGCAA
    76: CTACGTAGGT
    77: CTTCCTACTT
    78: TGGACCTTTG
    79: ATTGTACAGT
    80: TTCGCTTAAC
    81: TCGTACGATG
    82: AGTAGTTTGG
    83: TAACTGTAGT
    84: CCTAGGCAAA
    85: AGACGCATCT
    86: TCATATGTGA
    87: GACAATTGGG
    88: AGACGACCGA
    89: CGCGAGTAGG
    90: TCGCCATTTG
    91: AGCCTTCTCT
    92: TTAACGGACG
    93: TCGGGAGCTG
    94: CGCCCTCATC
    95: ATTGGCGCAA
    96: AGTGGAGGGA
