#Request types for Bait Capture Library
---
limber_bait_capture_library_prep:
  name: Bait Capture Library Preparation
  asset_type: Well
  order: 1
  request_class_name: Pulldown::Requests::IscLibraryRequest
  for_multiplexing: false
  billable: true
  product_line_name: Bait Capture Library
  library_types:
    - RVI-BCL
    - 10x RNA Flex
    - Parse Evercode
    - 16S rRNA
  acceptable_purposes:
    - RVI Cherrypick
