# These purposes reflect the old WGS pipelines that existed before Limber
# The file is marked as dev as we should have no need to update the pipelines in
# production.
---
ILB_STD_INPUT:
  type: PlatePurpose::Input
  stock_plate: true
  default_state: passed
  cherrypickable_target: true
ILB_STD_COVARIS:
  type: PlatePurpose::InitialPurpose
  cherrypickable_target: false
  source_purpose_name: ILB_STD_INPUT
ILB_STD_SH:
  cherrypickable_target: false
  source_purpose_name: ILB_STD_INPUT
ILB_STD_PREPCR:
  cherrypickable_target: false
  source_purpose_name: ILB_STD_INPUT
ILB_STD_PCR:
  cherrypickable_target: false
  source_purpose_name: ILB_STD_INPUT
ILB_STD_PCRR:
  cherrypickable_target: false
  source_purpose_name: ILB_STD_INPUT
ILB_STD_PCRXP:
  type: IlluminaHtp::FinalPlatePurpose
  cherrypickable_target: false
  source_purpose_name: ILB_STD_INPUT
ILB_STD_PCRRXP:
  type: IlluminaHtp::FinalPlatePurpose
  cherrypickable_target: false
  source_purpose_name: ILB_STD_INPUT
